version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: frac-miner_bitcoind_1
      APP_PORT: 8332
    
  # server:
  #   image: getumbrel/community-app-store-hello-world:latest
  #   user: "1000:1000"
  #   init: true
  bitcoind:
    image: fractalbitcoin/fractal:v0.1.7
    entrypoint: ["bitcoind", "-datadir=/data/", "-maxtipage=504576000"]
    command: ""
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data/", "getblockchaininfo"]
    networks:
      - fractal-bitcoin
    ports:
      - "8330:8330"
      - "8331:8331"
      - "8332:8332"
      - "8333:8333"
    deploy:
      resources:
        limits:
          memory: 8G
    memswap_limit: 60G
    mem_swappiness: 100
    volumes:
      - ./data:/data
    logging:
      driver: "json-file"
      options:
        labels: "env,filebeat,name"
        max-size: "1g"
        max-file: "3"
networks:
  fractal-bitcoin: